### ISSUE TITLE
bug in f2dWindowImpl::MoveToCenter

### ISSUE THREAD

**Issue by Xrysnow** [9chu/fancy2d#13]
问题：
* 当窗口矩形高度为奇数（常见于Windows10）时，MoveToCenter会错误地计算新的窗口矩形，导致实际画面高度少1。
https://github.com/9chu/fancy2d/blob/a780ae68c8cf54d9941bf71f281d1a9f8fd3174e/fancy2D/Engine/f2dWindowImpl.cpp#L804

😅

**Comment by 9chu** [comment]
Fixed
