### ISSUE TITLE
a bug in f2dFPSControllerImpl

### ISSUE THREAD

**Issue by Xrysnow** [9chu/fancy2d#15]
`timeBeginPeriod` 和 `timeEndPeriod` 应紧挨 `Sleep` ，否则会受到其他程序的影响。
https://github.com/9chu/fancy2d/blob/61c91e4edd6d13eeccdf6e15dd751a9b6b53c236/fancy2D/Engine/f2dFPSControllerImpl.h#L108-L118

**Comment by 9chu** [comment]
https://groups.google.com/forum/#!topic/borland.public.delphi.nativeapi.win32/FFV2KU62ht4

"Windows uses the lowest value (that is, highest resolution) requested by any process."
