### ISSUE TITLE
Garbled chinese code comments

### ISSUE THREAD

**Issue by cyf-gh** [9chu/fancy2d#8]
All chinese code comments in fancy2d's .cpp and .h files are garbled when opening in ASCI format.

**Comment by 9chu** [comment]
Using GBK/GB18030 encoding instead. I will change all source file's encoding into UTF-8 in future.

**Comment by lhmouse** [comment]
直接 iconv 啊。

**Comment by FrankHB** [comment]
渣渣 iconv 。

**Comment by cyf-gh** [comment]
请关爱我这样的弱逼(ノД`)
